accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name = 'accountapp/login.html'), name='login'),

    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'), # as_view(): CBV를 사용하기 위해 해당 뷰를 호출시킨다
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
urlpatterns = [

]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),

]

young2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp/urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/models.py
from django.db import models

# Create your models here.
class HelloWorld(models.Model): # Model을 상속 받는다
    text = models.CharField(max_length=255, null=False)

articleapp/models.py
from django.db import models

# Create your models here.

profileapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    # on_delete 옵션은 Django에서 모델을 구현할 때 데이터베이스 상에서 참조무결성을 유지하여
    # ForeignKeyField가 바라보는 값이 삭제될 때 해당 요소를 처리하는 방법을 지정해 준다.
    # CASCADE : ForeignKeyField를 포함하는 모델 인스턴스(row)도 같이 삭제한다.

    # profile 객체와 연결되어있는 user 객체를 거꾸로 불러올때, 이름으로 부르기 위해 related_name 설정

    image = models.ImageField(upload_to='profile/', null=True)
    nickname = models.CharField(max_length=30, unique=True, null=True)
    message = models.CharField(max_length=200, null=True)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/templates/accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm):
    def __init__(self,  *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

profileapp/forms.py
from django.forms import ModelForm

from profileapp.models import Profile


class ProfileCreationForm(ModelForm):
    class Meta:
        model = Profile # 어떤 모델을 기반으로 할 것인지
        fields = ['image', 'nickname', 'message'] # 클라이언트에게 받을 것

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountCreationForm
from accountapp.models import HelloWorld


@login_required()
def hello_world(request):
    # 라우팅 해줘야 해 (연결)
    # 메인 앱에서 먼저 받고 여기로 보냄
    if request.method == "POST":

        temp = request.POST.get('input')

        new_data = HelloWorld()
        new_data.text = temp
        new_data.save() # 실제 DB에 저장

        return HttpResponseRedirect(reverse('accountapp:hello_world')) # 실제 url 주소를 역치환해준다

        # data_list = HelloWorld.objects.all() # HelloWorld의 객체들을 가져온다
        # return render(request, 'accountapp/hello_world.html', context={'data_list' : data_list})
    else:
        data_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html', context={'data_list' : data_list})


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'

class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user' # html에서 객체를 불러오기 위해
    template_name = 'accountapp/detail.html'

has_ownership = [login_required, account_ownership_required]

# login이 돼있는지 여부만 판단하여 html을 보여준다
# login한 유저가 request의 유저와 같은지 여부를 판단하여 html을 보여준다
@method_decorator(has_ownership, 'get') # get방식 http에 적용해주겠다
@method_decorator(has_ownership, 'post') # post방식 http에 적용해주겠다
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountCreationForm
    context_object_name = 'target_user'
    template_name = 'accountapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail',kwargs={'pk': self.object.pk})


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/delete.html'

articleapp/views.py
from django.shortcuts import render

# Create your views here.

profileapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView

from profileapp.decorators import profile_ownership_required
from profileapp.forms import ProfileCreationForm
from profileapp.models import Profile


@method_decorator(login_required,'get')
class ProfileCreateView(CreateView):
    model = Profile
    form_class = ProfileCreationForm  # 어떤 폼을 입력받아서 할 것인지
    template_name = 'profileapp/create.html'


    def form_valid(self, form):  # form : 클라이언트가 데이터를 넣어놓은 ProfileCreationForm
        form.instance.user = self.request.user  # 유저 특정해주기, 폼이 생성되면
        return super().form_valid(form)

    def get_success_url(self):
       return reverse('accountapp:detail', kwargs={'pk':self.object.user.pk})

@method_decorator(profile_ownership_required,'get')
@method_decorator(profile_ownership_required,'post')
class ProfileUpdateView(UpdateView):
    model = Profile
    form_class = ProfileCreationForm
    context_object_name = 'target_profile'
    template_name = 'profileapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk':self.object.user.pk})

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Sign Up</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:create' %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                    <input type="submit" class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Quit</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
                {% csrf_token %}
                <div class="m-5">
                    <input type="submit" class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            {% if target_user.profile %}
                <img src="{{ target_user.profile.image.url }}"
                     class='profile_image m-4' alt="profile image">
                <h2 class="NNS_B">
                    {{ target_user.profile.nickname }}
                    {%  if target_user == user %}
                <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
                class = "material-icons round_button">
                  edit
                </a>
                    {% endif %}
                </h2>
                <h5>{{ target_user.profile.message }}</h5>
            {% else %}
                <h4>
                    <a href="{% url 'profileapp:create' %}">
                        Create Profile
                    </a>
                </h4>
            {% endif %}
        </div>
        <div>
            {{ target_user.date_joined }}
        </div>

        {% if user == target_user %}
            <div>
                <a href="{% url 'accountapp:update' pk=target_user.pk %}"
                  class="material-icons round_button mx=1">
                   settings
                </a>
                <a href="{% url 'accountapp:delete' pk=target_user.pk %}"
                   class="material-icons round_button mx=1">
                   close
                </a>
            </div>
        {% endif %}
    </div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}

    <div style="margin: 2rem; text-align: center;">
        <h1>METHOD</h1>

        <form action="/accounts/hello_world/" method="post">
            {% csrf_token %}
            <input type="text" name="input">
            <input type="submit" class="btn btn-dark rounded-pill px-5">
        </form>

        {% for data in data_list %}
            <h3>{{ data.text }}</h3>
        {% endfor %}
    </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Login</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:login' %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                    <input type="submit" class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Update info</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                    <input type="submit" class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

profileapp/templates/profileapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Create Profile</h4>
        </div>
        <div>
            <form action="{% url 'profileapp:create' %}" enctype="multipart/form-data" method="post">
                {# enctype : 폼 안에 넣는 데이터를 어떤 식으로 인코딩 할거냐, 파일은 문자열 처리하면 안되므로 해줘야 함 #}
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                    <input type="submit" class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

profileapp/templates/profileapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Update Profile</h4>
        </div>
        <div>
            <form action="{% url 'profileapp:update' pk=target_profile.pk %}"
                  enctype="multipart/form-data" method="post">
                {# enctype : 폼 안에 넣는 데이터를 어떤 식으로 인코딩 할거냐, 파일은 문자열 처리하면 안되므로 해줘야 함 #}
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                    <input type="submit" class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareR">

{% include 'header.html' %}

<hr>

{% block content %}
{% endblock %}

<hr>

{% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div style="text-align: center;">
    <div class="pragmatic_footer_button">
        <span>공지사항</span>
        <span>제휴문의</span>
        <span>서비스 소개</span>
    </div>
    <div class="pragmatic_footer_logo">
        <h5>Pragmatic</h5>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {# BOOTSTRAP LINK #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {# GOOGLE FONTS LINK #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">

    {# DEFAULT CSS LINK #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    {# METERIAL ICONS LINK#}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">


    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>
</head>

templates/header.html
<div style="text-align: center;">
    <div class="pragmatic_header_logo">
        <h1>Pragmatics</h1>
    </div>
    <div class="pragmatic_header_button">
        <span>nav1</span>
        <span>nav2</span>


        {% if not user.is_authenticated  %} {# 장고에서 언제든 user 객체를 불러올 수 있다#}
        <span>
            <a href="{% url 'accountapp:login' %}">
                Login
            </a>
        </span>
        <span>
            <a href="{% url 'accountapp:create' %}">
                Sign Up
            </a>
        </span>
        {% else %}
            <span>
                <a href="{% url 'accountapp:detail' pk=user.pk %}">
                    MyPage
                </a>
            </span>
            <span>
                <a href="{% url 'accountapp:logout' %}">
                    Logout
                </a>
            </span>
        {% endif %}


    </div>
</div>